#WIFI_SSID = "SHAW-892B"
#WIFI_PASSWORD = "eagle3127beside"

WIFI_SSID = "NOVAPixelPro"
WIFI_PASSWORD = "SuraDiha"


#telegram
botToken = "YOUR TELEGRAM BOT TOKEN"
#weather
weatherAPI = "Your Weather-API-KEY"
