#WIFI_SSID = "SHAW-892B"
#WIFI_PASSWORD = "eagle3127beside"

WIFI_SSID = "NOVAPixelPro"
WIFI_PASSWORD = "SuraDiha"


#telegram
botToken = "6844707988:AAFVAwaQb4Az2KoXOPTu2hjvbQovEyPrZp0"
weatherAPI = "9044c8a3784f6e27fe5a2053eda028f6"